inventions_2025 = {
    "Invention": [
        "Electric Salt Spoon", 
        "BoldJet Needle‑Free Injector", 
        "Petal Smart Garden Camera", 
        "Vivoo At‑Home Fertility Tests",
        "AI‑Matched Lipstick (O Boticário)",
        "Kara Pod (Air‑to‑Water Coffee Machine)",
        "Bee Pioneer Wearable AI",
        "NAQI Neural Earbuds",
        "Bio Leg (Bionic Prosthetic)",
        "booxtory AI Learning Platform",
        "BRAVIA Theater Quad Wireless Speakers",
        "HP Z Captis (3D/Spatial Capture)",
        "ScamVanguard (Anti‑Scam AI)",
        "TD Square (Tinnitus Digital Therapy)",
        "Drone First‑Responder Station",
        "Q‑Vision Pro On‑Device AI (Crime Prevention)",
        "Osmotex Electro‑osmotic Jacket",
        "Garmin inReach Messenger Plus"
    ],
    "Category": [
        "Food/Health Accessory",
        "MedTech / Drug Delivery",
        "Smart Home / Conservation",
        "Digital Health / FemTech",
        "Beauty Tech / AI Personalization",
        "Sustainability / Appliances",
        "Wearable AI",
        "Neurotech / Human‑Machine Interface",
        "Accessibility & AgeTech",
        "Artificial Intelligence / EdTech",
        "Audio/Video Accessories",
        "Computer Peripherals & Accessories",
        "Cybersecurity / Fraud Prevention",
        "Digital Health / Audiology",
        "Drones / Public Safety",
        "Embedded Technologies / Computer Vision",
        "Fashion Tech / Smart Textiles",
        "Mobile Devices / Satellite Messaging"
    ],
    "One_line_description": [
        "Handheld utensil that enhances saltiness perception to cut sodium intake.",
        "High‑pressure micro‑jet injector that delivers drugs without needles.",
        "Solar‑powered camera and habitat system that monitors pollinators in your yard.",
        "At‑home test strips with app insights for tracking fertility biomarkers.",
        "AI picks a lipstick shade that best matches your skin tone in‑store.",
        "Brews coffee and dispenses mineralized drinking water generated from air.",
        "Clip‑on/wrist wearable that summarizes your life and offers AI insights.",
        "Earbuds that read biosignals/micro‑gestures to control devices hands‑free.",
        "Powered prosthetic leg designed for smoother, natural gait and mobility.",
        "Story‑driven, AI‑tutored reading platform for kids.",
        "Modular wireless speaker system for cinematic surround without wires.",
        "Portable capture device for spatial/3D content creation workflows.",
        "AI system to detect and block phishing and scam attempts in real time.",
        "App‑guided tinnitus treatment device using digital therapeutics.",
        "Automated base enabling rapid drone dispatch for emergencies.",
        "On‑device AI vision platform aimed at real‑time crime prevention.",
        "Active membrane jacket that pumps moisture for comfort management.",
        "Satellite messenger with phone‑free SOS and two‑way texting."
    ],
    "Company_Organization": [
        "Kirin Holdings",
        "FlowBeams",
        "Bird Buddy Inc. (Wonder / Petal)",
        "Vivoo",
        "O Boticário",
        "Kara Water",
        "Bee (bee.computer)",
        "Naqi Logix Inc.",
        "BionicM Inc.",
        "Woongjin ThinkBig",
        "Sony Electronics",
        "HP Inc.",
        "SK Telecom",
        "Hanyang University Playlab",
        "Nearthlab",
        "Suprema AI",
        "Myant Corp.",
        "Garmin"
    ],
    "Country_Region": [
        "Japan",
        "Netherlands",
        "United States",
        "United States",
        "Brazil",
        "United States",
        "United States",
        "Canada",
        "Japan",
        "South Korea",
        "Japan",
        "United States",
        "South Korea",
        "South Korea",
        "South Korea",
        "South Korea",
        "Canada",
        "United States"
    ],
    "First_Announced": [
        "2025 (public spotlight via CES 2025 coverage)",
        "2025 (CES 2025 coverage)",
        "April 29, 2025 (Kickstarter launch)",
        "2025 (CES 2025 coverage)",
        "2025 (CES 2025 coverage)",
        "2025 (CES 2025 coverage)",
        "2025 (consumer launch)",
        "2025 (CES 2025 coverage)",
        "January 2025 (CES 2025 Best of Innovation)",
        "January 2025 (CES 2025 Best of Innovation)",
        "January 2025 (CES 2025 Best of Innovation)",
        "January 2025 (CES 2025 Best of Innovation)",
        "January 2025 (CES 2025 Best of Innovation)",
        "January 2025 (CES 2025 Best of Innovation)",
        "January 2025 (CES 2025 Best of Innovation)",
        "January 2025 (CES 2025 Best of Innovation)",
        "January 2025 (CES 2025 Best of Innovation)",
        "January 2025 (CES 2025 Best of Innovation)"
    ],
    "Availability_2025": [
        "On sale in Japan; showcased globally",
        "Prototype / pilot testing",
        "Preorder via crowdfunding; shipping phases in 2025–26",
        "Available in select markets (app + strips)",
        "In‑store trials/rollout in 2025",
        "Preorder/open sales in U.S. during 2025",
        "U.S. shipping (back‑ordered; iOS support)",
        "Pilot/early access units in 2025",
        "Pilots and early clinical deployments",
        "Commercial pilot / rollout in 2025",
        "Shipping in 2025",
        "Developer and pro workflows in 2025",
        "Carrier/service deployments in 2025",
        "Clinical/DTx pilot programs in 2025",
        "Deployed to agencies/partners in 2025",
        "Pilots with security partners in 2025",
        "Limited production runs in 2025",
        "Shipping in 2025"
    ],
    "Notable_spec_metric": [
        "Mild electrical stimulation enhances salty taste perception to reduce sodium.",
        "Supersonic micro‑jet forms through skin with minimal pain and waste.",
        "Solar‑powered; macro + wide lenses; pollinator activity insights in app.",
        "Urine‑based strips + app analytics for cycle tracking at home.",
        "Computer‑vision shade matching tailored to the wearer.",
        "Generates up to 3.2 L/day (Pod) or ~10 L/day (Pure 2) of mineralized water.",
        "Up to ~7 days battery; dual mics; iOS app + Apple Watch support.",
        "Detects brain waves/muscle impulses; hands‑free control (PC, mobility, etc.).",
        "Powered joints for adaptive gait and stairs/terrain support.",
        "Narrative ‘book movie’ AI with real‑time feedback.",
        "Wireless quad‑speaker surround for immersive home theater.",
        "Captures 3D/spatial data for XR and digital twins.",
        "AI flags scam patterns across calls/messages/links.",
        "Guided sound therapy protocols for tinnitus relief.",
        "Autonomous dock with rapid launch and charging.",
        "On‑device AI vision; rapid inference without the cloud.",
        "Electro‑osmotic moisture transport for active comfort.",
        "SOS + two‑way satellite messaging without a phone signal."
    ],
    "Source_URL": [
        "https://www.smithsonianmag.com/innovation/the-eight-coolest-inventions-from-the-2025-consumer-electronics-show-180985580/",
        "https://flowbeams.com/",
        "https://www.experiencewonder.com/",
        "https://www.smithsonianmag.com/innovation/the-eight-coolest-inventions-from-the-2025-consumer-electronics-show-180985580/",
        "https://www.smithsonianmag.com/innovation/the-eight-coolest-inventions-from-the-2025-consumer-electronics-show-180985580/",
        "https://www.karawater.com/",
        "https://www.bee.computer/",
        "https://www.naqilogix.com/",
        "https://www.ces.tech/press-releases/cta-announces-ces-2025-innovation-awards-honorees",
        "https://www.ces.tech/press-releases/cta-announces-ces-2025-innovation-awards-honorees",
        "https://www.ces.tech/press-releases/cta-announces-ces-2025-innovation-awards-honorees",
        "https://www.ces.tech/press-releases/cta-announces-ces-2025-innovation-awards-honorees",
        "https://www.ces.tech/press-releases/cta-announces-ces-2025-innovation-awards-honorees",
        "https://www.ces.tech/press-releases/cta-announces-ces-2025-innovation-awards-honorees",
        "https://www.ces.tech/press-releases/cta-announces-ces-2025-innovation-awards-honorees",
        "https://www.ces.tech/press-releases/cta-announces-ces-2025-innovation-awards-honorees",
        "https://www.ces.tech/press-releases/cta-announces-ces-2025-innovation-awards-honorees",
        "https://www.ces.tech/press-releases/cta-announces-ces-2025-innovation-awards-honorees"
    ]
}



